import tensorflow as tf
import tensorflow.keras.layers as layers

from darknetflow_poc.topologies.models.base_model import BaseModel

from darknetflow_poc.utils.constants import PAD_SAME, RELU, SIGMOID


class YoloV3Model(BaseModel):
    """
    Implementation of tf keras version of YOLO V3
    """
    def __init__(self, conf):
        super(YoloV3Model, self).__init__(conf)
        self.conv1 = layers.Conv2D(filters=32, kernel_size=3, strides=1, padding=PAD_SAME)
        # momentum = either 1 or 0 to shut off effects
        self.bn = layers.BatchNormalization(epsilon=1e-5, momentum=0.999, center=False, scale=True)
        self.conv2 = layers.Conv2D(filters=64, kernel_size=3, strides=2, padding=PAD_SAME)
        self.conv3 = layers.Conv2D(filters=32, kernel_size=1, strides=1, padding=PAD_SAME)
        self.conv4 = layers.Conv2D(filters=64, kernel_size=3, strides=1, padding=PAD_SAME)
        self.conv5 = layers.Conv2D(filters=128, kernel_size=3, strides=2, padding=PAD_SAME)
        self.conv6 = layers.Conv2D(filters=64, kernel_size=1, strides=1, padding=PAD_SAME)
        self.conv7 = layers.Conv2D(filters=128, kernel_size=3, strides=1, padding=PAD_SAME)
        self.conv8 = layers.Conv2D(filters=64, kernel_size=1, strides=1, padding=PAD_SAME)
        self.conv9 = layers.Conv2D(filters=128, kernel_size=3, strides=1, padding=PAD_SAME)
        self.conv10 = layers.Conv2D(filters=256, kernel_size=3, strides=2, padding=PAD_SAME)
        self.conv11 = layers.Conv2D(filters=128, kernel_size=1, strides=1, padding=PAD_SAME)
        self.conv12 = layers.Conv2D(filters=256, kernel_size=3, strides=1, padding=PAD_SAME)
        self.conv13 = layers.Conv2D(filters=128, kernel_size=1, strides=1, padding=PAD_SAME)
        self.conv14 = layers.Conv2D(filters=256, kernel_size=3, strides=1, padding=PAD_SAME)
        self.conv15 = layers.Conv2D(filters=128, kernel_size=1, strides=1, padding=PAD_SAME)
        self.conv16 = layers.Conv2D(filters=256, kernel_size=3, strides=1, padding=PAD_SAME)
        self.conv17 = layers.Conv2D(filters=128, kernel_size=1, strides=1, padding=PAD_SAME)
        self.conv18 = layers.Conv2D(filters=256, kernel_size=3, strides=1, padding=PAD_SAME)
        self.conv19 = layers.Conv2D(filters=128, kernel_size=1, strides=1, padding=PAD_SAME)
        self.conv20 = layers.Conv2D(filters=256, kernel_size=3, strides=1, padding=PAD_SAME)
        self.conv21 = layers.Conv2D(filters=128, kernel_size=1, strides=1, padding=PAD_SAME)
        self.conv22 = layers.Conv2D(filters=256, kernel_size=3, strides=1, padding=PAD_SAME)
        self.conv23 = layers.Conv2D(filters=128, kernel_size=1, strides=1, padding=PAD_SAME)
        self.conv24 = layers.Conv2D(filters=256, kernel_size=3, strides=1, padding=PAD_SAME)
        self.conv25 = layers.Conv2D(filters=128, kernel_size=1, strides=1, padding=PAD_SAME)
        self.conv26 = layers.Conv2D(filters=256, kernel_size=3, strides=1, padding=PAD_SAME)
        self.conv27 = layers.Conv2D(filters=512, kernel_size=3, strides=2, padding=PAD_SAME)
        self.conv28 = layers.Conv2D(filters=256, kernel_size=1, strides=1, padding=PAD_SAME)
        self.conv29 = layers.Conv2D(filters=512, kernel_size=3, strides=1, padding=PAD_SAME)
        self.conv30 = layers.Conv2D(filters=256, kernel_size=1, strides=1, padding=PAD_SAME)
        self.conv31 = layers.Conv2D(filters=512, kernel_size=3, strides=1, padding=PAD_SAME)
        self.conv32 = layers.Conv2D(filters=256, kernel_size=1, strides=1, padding=PAD_SAME)
        self.conv33 = layers.Conv2D(filters=512, kernel_size=3, strides=1, padding=PAD_SAME)
        self.conv34 = layers.Conv2D(filters=256, kernel_size=1, strides=1, padding=PAD_SAME)
        self.conv35 = layers.Conv2D(filters=512, kernel_size=3, strides=1, padding=PAD_SAME)
        self.conv36 = layers.Conv2D(filters=256, kernel_size=1, strides=1, padding=PAD_SAME)
        self.conv37 = layers.Conv2D(filters=512, kernel_size=3, strides=1, padding=PAD_SAME)
        self.conv38 = layers.Conv2D(filters=256, kernel_size=1, strides=1, padding=PAD_SAME)
        self.conv39 = layers.Conv2D(filters=512, kernel_size=3, strides=1, padding=PAD_SAME)
        self.conv40 = layers.Conv2D(filters=256, kernel_size=1, strides=1, padding=PAD_SAME)
        self.conv41 = layers.Conv2D(filters=512, kernel_size=3, strides=1, padding=PAD_SAME)
        self.conv42 = layers.Conv2D(filters=256, kernel_size=1, strides=1, padding=PAD_SAME)
        self.conv43 = layers.Conv2D(filters=512, kernel_size=3, strides=1, padding=PAD_SAME)
        self.conv44 = layers.Conv2D(filters=1024, kernel_size=3, strides=2, padding=PAD_SAME)
        self.conv45 = layers.Conv2D(filters=512, kernel_size=1, strides=1, padding=PAD_SAME)
        self.conv46 = layers.Conv2D(filters=1024, kernel_size=3, strides=1, padding=PAD_SAME)
        self.conv47 = layers.Conv2D(filters=512, kernel_size=1, strides=1, padding=PAD_SAME)
        self.conv48 = layers.Conv2D(filters=1024, kernel_size=3, strides=1, padding=PAD_SAME)
        self.conv49 = layers.Conv2D(filters=512, kernel_size=1, strides=1, padding=PAD_SAME)
        self.conv50 = layers.Conv2D(filters=1024, kernel_size=3, strides=1, padding=PAD_SAME)
        self.conv51 = layers.Conv2D(filters=512, kernel_size=1, strides=1, padding=PAD_SAME)
        self.conv52 = layers.Conv2D(filters=1024, kernel_size=3, strides=1, padding=PAD_SAME)
        self.conv53 = layers.Conv2D(filters=512, kernel_size=1, strides=1, padding=PAD_SAME)
        self.conv54 = layers.Conv2D(filters=1024, kernel_size=3, strides=1, padding=PAD_SAME)
        self.conv55 = layers.Conv2D(filters=512, kernel_size=1, strides=1, padding=PAD_SAME)
        self.conv56 = layers.Conv2D(filters=1024, kernel_size=3, strides=1, padding=PAD_SAME)
        self.conv57 = layers.Conv2D(filters=512, kernel_size=1, strides=1, padding=PAD_SAME)
        self.conv58 = layers.Conv2D(filters=1024, kernel_size=3, strides=1, padding=PAD_SAME)
        self.conv59 = layers.Conv2D(filters=255, kernel_size=1, strides=1, padding=PAD_SAME)

    def call(self, inputs):
        print('0 - Input: {}'.format(inputs.shape))
        inputs = self.conv1(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('1 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv2(inputs)
        inputs = shortcut = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('2 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv3(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('3 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv4(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('4 - Conv2D: {}'.format(inputs.shape))
        inputs = tf.add(inputs, shortcut)
        print('5 - Shortcut: {}'.format(inputs.shape))
        inputs = shortcut = self.conv5(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('6 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv6(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('7 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv7(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('8 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('9 - Shortcut: {}'.format(inputs.shape))
        inputs = self.conv8(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('10 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv9(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('11 - Conv2D: {}'.format(inputs.shape))
        inputs = tf.add(inputs, shortcut)
        print('12 - Shortcut: {}'.format(inputs.shape))
        inputs = self.conv10(inputs)
        inputs = shortcut = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('13 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv11(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('14 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv12(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('15 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('16 - Shortcut: {}'.format(inputs.shape))
        inputs = self.conv13(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('17 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv14(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('18 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('19 - Shortcut: {}'.format(inputs.shape))
        inputs = self.conv15(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('20 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv16(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('21 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('22 - Shortcut: {}'.format(inputs.shape))
        inputs = self.conv17(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('23 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv18(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('24 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('25 - Shortcut: {}'.format(inputs.shape))
        inputs = self.conv19(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('26 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv20(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('27 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('28 - Shortcut: {}'.format(inputs.shape))
        inputs = self.conv21(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('29 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv22(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('30 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('31 - Shortcut: {}'.format(inputs.shape))
        inputs = self.conv23(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('32 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv24(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('33 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('34 - Shortcut: {}'.format(inputs.shape))
        inputs = self.conv25(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('35 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv26(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('36 - Conv2D: {}'.format(inputs.shape))
        inputs = resout1 = tf.add(inputs, shortcut)
        print('37 - Shortcut: {}'.format(inputs.shape))
        inputs = self.conv27(inputs)
        inputs = shortcut = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('38 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv28(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('39 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv29(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('40 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('41 - Shortcut: {}'.format(inputs.shape))
        inputs = self.conv30(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('42 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv31(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('43 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('44 - Shortcut: {}'.format(inputs.shape))
        inputs = self.conv32(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('45 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv33(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('46 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('47 - Shortcut: {}'.format(inputs.shape))
        inputs = self.conv34(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('48 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv35(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('49 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('50 - Shortcut: {}'.format(inputs.shape))
        inputs = self.conv36(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('51 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv37(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('52 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('53 - Shortcut: {}'.format(inputs.shape))
        inputs = self.conv38(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('54 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv39(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('55 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('56 - Shortcut: {}'.format(inputs.shape))
        inputs = self.conv40(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('57 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv41(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('58 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('59 - Shortcut: {}'.format(inputs.shape))
        inputs = self.conv42(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('60 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv43(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('61 - Conv2D: {}'.format(inputs.shape))
        inputs = resout2 = tf.add(inputs, shortcut)
        print('62 - Shortcut: {}'.format(inputs.shape))
        inputs = self.conv44(inputs)
        inputs = shortcut = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('63 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv45(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('64 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv46(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('65 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('66 - Shortcut: {}'.format(inputs.shape))
        inputs = self.conv47(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('67 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv48(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('68 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('69 - Shortcut: {}'.format(inputs.shape))
        inputs = self.conv49(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('70 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv50(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('71 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('72 - Shortcut: {}'.format(inputs.shape))
        inputs = self.conv51(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('73 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv52(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('74 - Conv2D: {}'.format(inputs.shape))
        inputs = tf.add(inputs, shortcut)
        print('75 - Shortcut: {}'.format(inputs.shape))
        inputs = self.conv53(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('76 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv54(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('77 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv55(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('78 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv56(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('79 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv57(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('80 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv58(inputs)
        inputs = self.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('81 - Conv2D: {}'.format(inputs.shape))
        inputs = self.conv59(inputs)
        print('82 - Conv2D: {}'.format(inputs.shape))

        return inputs
