import tensorflow as tf
import tensorflow.keras.layers as layers

from object_detection_poc.topologies.models.base_model import BaseModel, ModelLayers
from object_detection_poc.topologies.layers.yolo_v3_layer import YoloV3Layer

from object_detection_poc.utils.constants import PAD_SAME, RELU, SIGMOID, PAD_VALID


class YoloV3Model(BaseModel):
    """
    Implementation of tf keras version of YOLO V3
    """
    def __init__(self, conf):
        super(YoloV3Model, self).__init__(conf)
        model_layers = ModelLayers()
        model_layers.conv1 = layers.Conv2D(filters=32, kernel_size=3, strides=1, padding=PAD_SAME)
        # momentum = either 1 or 0 to shut off effects
        model_layers.bn = layers.BatchNormalization(epsilon=1e-5, momentum=0.999, center=False, scale=True)
        model_layers.conv2 = layers.Conv2D(filters=64, kernel_size=3, strides=2, padding=PAD_SAME)
        model_layers.conv3 = layers.Conv2D(filters=32, kernel_size=1, strides=1, padding=PAD_SAME)
        model_layers.conv4 = layers.Conv2D(filters=64, kernel_size=3, strides=1, padding=PAD_SAME)
        model_layers.conv5 = layers.Conv2D(filters=128, kernel_size=3, strides=2, padding=PAD_SAME)
        model_layers.conv6 = layers.Conv2D(filters=64, kernel_size=1, strides=1, padding=PAD_SAME)
        model_layers.conv7 = layers.Conv2D(filters=128, kernel_size=3, strides=1, padding=PAD_SAME)
        model_layers.conv8 = layers.Conv2D(filters=64, kernel_size=1, strides=1, padding=PAD_SAME)
        model_layers.conv9 = layers.Conv2D(filters=128, kernel_size=3, strides=1, padding=PAD_SAME)
        model_layers.conv10 = layers.Conv2D(filters=256, kernel_size=3, strides=2, padding=PAD_SAME)
        model_layers.conv11 = layers.Conv2D(filters=128, kernel_size=1, strides=1, padding=PAD_SAME)
        model_layers.conv12 = layers.Conv2D(filters=256, kernel_size=3, strides=1, padding=PAD_SAME)
        model_layers.conv13 = layers.Conv2D(filters=128, kernel_size=1, strides=1, padding=PAD_SAME)
        model_layers.conv14 = layers.Conv2D(filters=256, kernel_size=3, strides=1, padding=PAD_SAME)
        model_layers.conv15 = layers.Conv2D(filters=128, kernel_size=1, strides=1, padding=PAD_SAME)
        model_layers.conv16 = layers.Conv2D(filters=256, kernel_size=3, strides=1, padding=PAD_SAME)
        model_layers.conv17 = layers.Conv2D(filters=128, kernel_size=1, strides=1, padding=PAD_SAME)
        model_layers.conv18 = layers.Conv2D(filters=256, kernel_size=3, strides=1, padding=PAD_SAME)
        model_layers.conv19 = layers.Conv2D(filters=128, kernel_size=1, strides=1, padding=PAD_SAME)
        model_layers.conv20 = layers.Conv2D(filters=256, kernel_size=3, strides=1, padding=PAD_SAME)
        model_layers.conv21 = layers.Conv2D(filters=128, kernel_size=1, strides=1, padding=PAD_SAME)
        model_layers.conv22 = layers.Conv2D(filters=256, kernel_size=3, strides=1, padding=PAD_SAME)
        model_layers.conv23 = layers.Conv2D(filters=128, kernel_size=1, strides=1, padding=PAD_SAME)
        model_layers.conv24 = layers.Conv2D(filters=256, kernel_size=3, strides=1, padding=PAD_SAME)
        model_layers.conv25 = layers.Conv2D(filters=128, kernel_size=1, strides=1, padding=PAD_SAME)
        model_layers.conv26 = layers.Conv2D(filters=256, kernel_size=3, strides=1, padding=PAD_SAME)
        model_layers.conv27 = layers.Conv2D(filters=512, kernel_size=3, strides=2, padding=PAD_SAME)
        model_layers.conv28 = layers.Conv2D(filters=256, kernel_size=1, strides=1, padding=PAD_SAME)
        model_layers.conv29 = layers.Conv2D(filters=512, kernel_size=3, strides=1, padding=PAD_SAME)
        model_layers.conv30 = layers.Conv2D(filters=256, kernel_size=1, strides=1, padding=PAD_SAME)
        model_layers.conv31 = layers.Conv2D(filters=512, kernel_size=3, strides=1, padding=PAD_SAME)
        model_layers.conv32 = layers.Conv2D(filters=256, kernel_size=1, strides=1, padding=PAD_SAME)
        model_layers.conv33 = layers.Conv2D(filters=512, kernel_size=3, strides=1, padding=PAD_SAME)
        model_layers.conv34 = layers.Conv2D(filters=256, kernel_size=1, strides=1, padding=PAD_SAME)
        model_layers.conv35 = layers.Conv2D(filters=512, kernel_size=3, strides=1, padding=PAD_SAME)
        model_layers.conv36 = layers.Conv2D(filters=256, kernel_size=1, strides=1, padding=PAD_SAME)
        model_layers.conv37 = layers.Conv2D(filters=512, kernel_size=3, strides=1, padding=PAD_SAME)
        model_layers.conv38 = layers.Conv2D(filters=256, kernel_size=1, strides=1, padding=PAD_SAME)
        model_layers.conv39 = layers.Conv2D(filters=512, kernel_size=3, strides=1, padding=PAD_SAME)
        model_layers.conv40 = layers.Conv2D(filters=256, kernel_size=1, strides=1, padding=PAD_SAME)
        model_layers.conv41 = layers.Conv2D(filters=512, kernel_size=3, strides=1, padding=PAD_SAME)
        model_layers.conv42 = layers.Conv2D(filters=256, kernel_size=1, strides=1, padding=PAD_SAME)
        model_layers.conv43 = layers.Conv2D(filters=512, kernel_size=3, strides=1, padding=PAD_SAME)
        model_layers.conv44 = layers.Conv2D(filters=1024, kernel_size=3, strides=2, padding=PAD_SAME)
        model_layers.conv45 = layers.Conv2D(filters=512, kernel_size=1, strides=1, padding=PAD_SAME)
        model_layers.conv46 = layers.Conv2D(filters=1024, kernel_size=3, strides=1, padding=PAD_SAME)
        model_layers.conv47 = layers.Conv2D(filters=512, kernel_size=1, strides=1, padding=PAD_SAME)
        model_layers.conv48 = layers.Conv2D(filters=1024, kernel_size=3, strides=1, padding=PAD_SAME)
        model_layers.conv49 = layers.Conv2D(filters=512, kernel_size=1, strides=1, padding=PAD_SAME)
        model_layers.conv50 = layers.Conv2D(filters=1024, kernel_size=3, strides=1, padding=PAD_SAME)
        model_layers.conv51 = layers.Conv2D(filters=512, kernel_size=1, strides=1, padding=PAD_SAME)
        model_layers.conv52 = layers.Conv2D(filters=1024, kernel_size=3, strides=1, padding=PAD_SAME)
        model_layers.conv53 = layers.Conv2D(filters=512, kernel_size=1, strides=1, padding=PAD_SAME)
        model_layers.conv54 = layers.Conv2D(filters=1024, kernel_size=3, strides=1, padding=PAD_SAME)
        model_layers.conv55 = layers.Conv2D(filters=512, kernel_size=1, strides=1, padding=PAD_SAME)
        model_layers.conv56 = layers.Conv2D(filters=1024, kernel_size=3, strides=1, padding=PAD_SAME)
        model_layers.conv57 = layers.Conv2D(filters=512, kernel_size=1, strides=1, padding=PAD_SAME)
        model_layers.conv58 = layers.Conv2D(filters=1024, kernel_size=3, strides=1, padding=PAD_SAME)
        model_layers.conv59 = layers.Conv2D(filters=255, kernel_size=1, strides=1, padding=PAD_SAME)
        model_layers.yolo1 = YoloV3Layer(anchors=[(116, 90), (156, 198), (373, 326)], conf=conf)
        self.model_layers = model_layers

    def call(self, inputs):
        model_layers = self.model_layers
        print('0 - Input: {}'.format(inputs.shape))
        inputs = model_layers.conv1(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('1 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv2(inputs)
        inputs = shortcut = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('2 - Conv2D: {}'.format(inputs.shape))
        print('Check2', inputs)
        inputs = model_layers.conv3(inputs)
        print('Check3', inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('3 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv4(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('4 - Conv2D: {}'.format(inputs.shape))
        inputs = tf.add(inputs, shortcut)
        print('5 - Shortcut: {}'.format(inputs.shape))
        inputs = shortcut = model_layers.conv5(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('6 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv6(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('7 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv7(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('8 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('9 - Shortcut: {}'.format(inputs.shape))
        inputs = model_layers.conv8(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('10 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv9(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('11 - Conv2D: {}'.format(inputs.shape))
        inputs = tf.add(inputs, shortcut)
        print('12 - Shortcut: {}'.format(inputs.shape))
        inputs = model_layers.conv10(inputs)
        inputs = shortcut = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('13 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv11(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('14 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv12(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('15 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('16 - Shortcut: {}'.format(inputs.shape))
        inputs = model_layers.conv13(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('17 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv14(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('18 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('19 - Shortcut: {}'.format(inputs.shape))
        inputs = model_layers.conv15(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('20 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv16(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('21 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('22 - Shortcut: {}'.format(inputs.shape))
        inputs = model_layers.conv17(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('23 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv18(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('24 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('25 - Shortcut: {}'.format(inputs.shape))
        inputs = model_layers.conv19(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('26 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv20(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('27 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('28 - Shortcut: {}'.format(inputs.shape))
        inputs = model_layers.conv21(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('29 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv22(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('30 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('31 - Shortcut: {}'.format(inputs.shape))
        inputs = model_layers.conv23(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('32 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv24(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('33 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('34 - Shortcut: {}'.format(inputs.shape))
        inputs = model_layers.conv25(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('35 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv26(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('36 - Conv2D: {}'.format(inputs.shape))
        inputs = resout1 = tf.add(inputs, shortcut)
        print('37 - Shortcut: {}'.format(inputs.shape))
        inputs = model_layers.conv27(inputs)
        inputs = shortcut = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('38 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv28(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('39 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv29(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('40 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('41 - Shortcut: {}'.format(inputs.shape))
        inputs = model_layers.conv30(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('42 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv31(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('43 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('44 - Shortcut: {}'.format(inputs.shape))
        inputs = model_layers.conv32(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('45 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv33(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('46 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('47 - Shortcut: {}'.format(inputs.shape))
        inputs = model_layers.conv34(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('48 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv35(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('49 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('50 - Shortcut: {}'.format(inputs.shape))
        inputs = model_layers.conv36(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('51 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv37(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('52 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('53 - Shortcut: {}'.format(inputs.shape))
        inputs = model_layers.conv38(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('54 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv39(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('55 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('56 - Shortcut: {}'.format(inputs.shape))
        inputs = model_layers.conv40(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('57 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv41(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('58 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('59 - Shortcut: {}'.format(inputs.shape))
        inputs = model_layers.conv42(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('60 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv43(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('61 - Conv2D: {}'.format(inputs.shape))
        inputs = resout2 = tf.add(inputs, shortcut)
        print('62 - Shortcut: {}'.format(inputs.shape))
        inputs = model_layers.conv44(inputs)
        inputs = shortcut = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('63 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv45(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('64 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv46(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('65 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('66 - Shortcut: {}'.format(inputs.shape))
        inputs = model_layers.conv47(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('67 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv48(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('68 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('69 - Shortcut: {}'.format(inputs.shape))
        inputs = model_layers.conv49(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('70 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv50(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('71 - Conv2D: {}'.format(inputs.shape))
        inputs = shortcut = tf.add(inputs, shortcut)
        print('72 - Shortcut: {}'.format(inputs.shape))
        inputs = model_layers.conv51(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('73 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv52(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('74 - Conv2D: {}'.format(inputs.shape))
        inputs = tf.add(inputs, shortcut)
        print('75 - Shortcut: {}'.format(inputs.shape))
        inputs = model_layers.conv53(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('76 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv54(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('77 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv55(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('78 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv56(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('79 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv57(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('80 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv58(inputs)
        inputs = model_layers.bn(tf.nn.leaky_relu(features=inputs, alpha=0.1))
        print('81 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.conv59(inputs)
        print('82 - Conv2D: {}'.format(inputs.shape))
        inputs = model_layers.yolo1(inputs)
        print('83 - YoloV3: {}'.format(inputs.shape))

        return inputs
